/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        cyber: {
          bg: "rgb(var(--color-cyber-bg) / <alpha-value>)",
          surface: "rgb(var(--color-cyber-surface) / <alpha-value>)",
          overlay: "rgb(var(--color-cyber-overlay) / <alpha-value>)",
          cyan: "rgb(var(--color-cyber-cyan) / <alpha-value>)",
          magenta: "rgb(var(--color-cyber-magenta) / <alpha-value>)",
          green: "rgb(var(--color-cyber-green) / <alpha-value>)",
          purple: "rgb(var(--color-cyber-purple) / <alpha-value>)",
          blue: "rgb(var(--color-cyber-blue) / <alpha-value>)",
          amber: "rgb(var(--color-cyber-amber) / <alpha-value>)",
          text: "rgb(var(--color-cyber-text) / <alpha-value>)",
          "text-secondary": "rgb(var(--color-cyber-text-secondary) / <alpha-value>)",
        },
      },
      fontFamily: {
        "heading": ["JetBrainsMono_700Bold", "monospace"],
        "heading-medium": ["JetBrainsMono_500Medium", "monospace"],
        "body": ["Inter_400Regular", "sans-serif"],
        "body-medium": ["Inter_500Medium", "sans-serif"],
        "body-semibold": ["Inter_600SemiBold", "sans-serif"],
        "mono": ["SpaceMono_400Regular", "monospace"],
      },
      fontSize: {
        "2xs": ["10px", { lineHeight: "14px" }],
        "xs": ["12px", { lineHeight: "16px" }],
        "sm": ["14px", { lineHeight: "20px" }],
        "base": ["16px", { lineHeight: "24px" }],
        "lg": ["18px", { lineHeight: "28px" }],
        "xl": ["20px", { lineHeight: "28px" }],
        "2xl": ["24px", { lineHeight: "32px" }],
        "3xl": ["30px", { lineHeight: "36px" }],
        "4xl": ["36px", { lineHeight: "40px" }],
      },
      spacing: {
        "0.5": "2px",
        "1": "4px",
        "2": "8px",
        "3": "12px",
        "4": "16px",
        "5": "20px",
        "6": "24px",
        "8": "32px",
        "10": "40px",
        "12": "48px",
        "16": "64px",
      },
      borderRadius: {
        "card": "8px",
        "button": "12px",
        "pill": "24px",
        "full": "9999px",
      },
      boxShadow: {
        "neon-cyan": "0 0 10px rgba(0, 255, 255, 0.3), 0 0 20px rgba(0, 255, 255, 0.1)",
        "neon-cyan-strong": "0 0 15px rgba(0, 255, 255, 0.5), 0 0 30px rgba(0, 255, 255, 0.2)",
        "neon-magenta": "0 0 10px rgba(255, 0, 102, 0.3), 0 0 20px rgba(255, 0, 102, 0.1)",
        "neon-green": "0 0 10px rgba(0, 255, 136, 0.3), 0 0 20px rgba(0, 255, 136, 0.1)",
        "neon-purple": "0 0 10px rgba(139, 92, 246, 0.3), 0 0 20px rgba(139, 92, 246, 0.1)",
      },
    },
  },
  plugins: [],
};
